app = "workers"
kill_signal = "SIGINT"
primary_region = "otp"
kill_timeout = 5
[env]
  DEBUG = false
[experimental]
  auto_rollback = true
[processes]
  worker = "celery -A auto worker -l WARNING -Q beat_tasks"
  bot_worker = "celery -A auto worker -l WARNING -Q bot_tasks"
  beat = "celery -A auto beat -l WARNING"